pipeline:
  identifier: Build_rahkumar56_1698232738943
  name: Build rahkumar56
  orgIdentifier: default
  projectIdentifier: Test_Log_Service_project
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    shell: Sh
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            os: Linux
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths: []
        type: CI
  delegateSelectors:
    - rahulk-delegate-nikaw
