pipeline:
  identifier: Build_rahkumar56_1698232738943
  name: Build rahkumar56
  orgIdentifier: default
  projectIdentifier: Test_Log_Service_project
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine:latest
                    shell: Sh
                    command: echo hello world
                  timeout: ""
                  type: Run
          caching:
            enabled: false
            paths: []
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: rahulscaletest
              namespace: rahul-scaletest
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
  allowStageExecutions: true
